TITTLE_AKAS_URL = 'https://datasets.imdbws.com/title.akas.tsv.gz'
TITTLE_BASICS_URL = 'https://datasets.imdbws.com/title.basics.tsv.gz'
TITTLE_CREW_URL = 'https://datasets.imdbws.com/title.crew.tsv.gz'
TITTLE_EPISODES_URL = 'https://datasets.imdbws.com/title.episode.tsv.gz'
TITTLE_PRINCIPALS_URL = 'https://datasets.imdbws.com/title.principals.tsv.gz'
TITTLE_RATINGS_URL = 'https://datasets.imdbws.com/title.ratings.tsv.gz'
NAME_BASICS_URL = 'https://datasets.imdbws.com/name.basics.tsv.gz'